"""
IntelliJudge — TestCase Model

Maps to the "test_cases" table. Test cases belong to a Problem and are used
by the Judge0 compiler service to verify submitted code.

CATEGORIES:
  - "sample"  : Visible sample cases from the problem statement
  - "hidden"  : Hidden cases used only during submission judging
  - "edge"    : Edge cases generated by the AI (e.g. empty input, max values)
  - "stress"  : Stress tests for performance verification

is_visible:
  True  → shown to the user in the problem view (sample cases)
  False → hidden, only used for judging (hidden/edge/stress cases)
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import Boolean, DateTime, ForeignKey, String, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base

if TYPE_CHECKING:
    from app.models.problem import Problem


class TestCase(Base):
    """
    A single input/output pair used to judge a submission.
    """

    __tablename__ = "test_cases"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=func.gen_random_uuid(),
    )

    problem_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("problems.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    input: Mapped[str] = mapped_column(Text, nullable=False)
    expected_output: Mapped[str] = mapped_column(Text, nullable=False)

    # "sample" | "hidden" | "edge" | "stress"
    category: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        default="sample",
        server_default="sample",
    )

    # Whether the user can see this test case in the problem view
    is_visible: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
        server_default="true",
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )

    # ─── Relationships ─────────────────────────────────────────

    problem: Mapped["Problem"] = relationship("Problem", back_populates="test_cases")

    def __repr__(self) -> str:
        return (
            f"<TestCase(id={self.id}, problem_id={self.problem_id}, "
            f"category={self.category!r}, visible={self.is_visible})>"
        )
